#! /bin/python3

import sys, os
from string import Template

mode = sys.argv[1]
page_name = sys.argv[2]

vue_name = "".join( [ key.capitalize() for key in page_name.split("-")])
if mode == "admin":
    html_fn = "admin/"+page_name+".html"
    js_fn = "src/entry/admin/"+page_name+".js"
    vue_fn = "pages/admin/"+vue_name+".vue"
else:
    html_fn = page_name+".html"
    js_fn = "src/entry/oj/"+page_name+".js"
    vue_fn = "pages/oj/"+vue_name+".vue"

#print( html_fn, js_fn, vue_fn )
if os.path.exists(html_fn):
    print("exists")
    exit(0)

HTML="""
<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/png" sizes="32x32" href="/icon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>软工在线测试平台</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/${name}"></script>
  </body>
</html>
"""

JS="""
import initApp from "@/entry/initapp";
import App from '@/${name}';
const app = initApp(App).mount("#app");
"""

VUE="""
<script setup>
import NavBar from '@/components/NavBar.vue'
import XMUTFooter from '@/components/XMUTFooter.vue'
import TitledPanel from '../../components/TitledPanel.vue';
import { ref, reactive, onMounted, resolveComponent } from 'vue';
import i18n from '@/i18n';
import api from '@/api';
import utils from '@/utils';

const query = reactive({keyword:'', page:1, limit:15, total:0 });

const filterByKeyword = function(){
}

const onReset = function(){
}

const userInfo = ref({login:false});

onMounted(() => {
})
</script>

<template>
  <Layout>
    <NavBar :activeMenu="'${name}'" v-model="userInfo"></NavBar>
    <div class="content-app">
      <Content :style="{padding:'0 50px'}">
        <TitledPanel>
          <template #title>
            测试
          </template>
          <template #extra>
            <ul class="filter">
              <li>
                <Input v-model="query.keyword" @on-enter="filterByKeyword" @on-click="filterByKeyword"
                  placeholder="关键字" icon="ios-search-strong" />
              </li>
              <li>
                <Button type="primary" @click="onReset">
                  <Icon type="md-refresh"></Icon>
                   重置
                </Button>
              </li>
            </ul>
          </template>
        </TitledPanel>
      </Content>
    </div>
    <XMUTFooter></XMUTFooter>
  </Layout>
</template>

<style>
.ivu-btn{
  margin-right: 10px;
  margin-left: 10px;
}

.operation .ivu-btn{
  margin-right: 1px;
  margin-left: 1px;
}
</style>
"""

VUE_ADMIN="""
<script setup>
import NavBarAdmin from '@/components/NavBarAdmin.vue'
import XMUTFooter from '@/components/XMUTFooter.vue'
import TitledPanel from '../../components/TitledPanel.vue';
import { ref, reactive, onMounted, resolveComponent } from 'vue';
import i18n from '@/i18n';
import api from '@/api';
import utils from '@/utils';

const query = reactive({keyword:'', page:1, limit:15, total:0 });

const filterByKeyword = function(){
}

const onReset = function(){
}

const userInfo = ref({login:false});

onMounted(() => {
})
</script>

<template>
  <Layout>
    <NavBarAdmin :activeMenu="'./${name}'" v-model="userInfo"></NavBarAdmin>
    <div class="content-app">
      <Content :style="{padding:'0 50px'}">
        <TitledPanel>
          <template #title>
            测试
          </template>
          <template #extra>
            <ul class="filter">
              <li>
                <Input v-model="query.keyword" @on-enter="filterByKeyword" @on-click="filterByKeyword"
                  placeholder="关键字" icon="ios-search-strong" />
              </li>
              <li>
                <Button type="primary" @click="onReset">
                  <Icon type="md-refresh"></Icon>
                   重置
                </Button>
              </li>
            </ul>
          </template>
        </TitledPanel>
      </Content>
    </div>
    <XMUTFooter></XMUTFooter>
  </Layout>
</template>

<style>
.ivu-btn{
  margin-right: 10px;
  margin-left: 10px;
}

.operation .ivu-btn{
  margin-right: 1px;
  margin-left: 1px;
}
</style>
"""

HTML = Template(HTML).substitute(name=js_fn)
JS = Template(JS).substitute(name=vue_fn)
if mode == "admin":
    print(html_fn)
    VUE = Template(VUE_ADMIN).substitute(name=html_fn)
else:
    VUE = Template(VUE).substitute(name=html_fn)

print("==============================================")
print(html_fn)
print("==============================================")
print(HTML)
print("==============================================")
print(js_fn)
print("==============================================")
print(JS)
print("==============================================")
print(vue_fn)
print("==============================================")
print(VUE)
open(html_fn,"w").write(HTML)
open(js_fn,"w").write(JS)
open("src/"+vue_fn,"w").write(VUE)
